AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5
  Exclude:
    - build/**/*
    - vendor/**/*

Metrics/LineLength:
  Max: 180

Metrics/ParameterLists:
  Max: 10

Documentation:
  Enabled: false
